server:
  port: 8888
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: config-server
 cloud:
  config:
   server:
    git:
      uri: https://github.com/cthet/corporation-config-server-repo
      clone-on-start: true
      default-label: main